import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { APPEARANCE_BOOT_SCRIPT } from "@/hooks/useAppearance";
import { Spinner } from "@/components/ios/Spinner";
import splashScreens from "@/generated/splash-screens.json";

export const metadata: Metadata = {
    title: "Messages",
    description: "Read and send SMS through your Android gateway.",
    applicationName: "SMS Gateway",
    manifest: "/manifest.webmanifest",
    icons: {
        icon: [
            { url: "/favicon.svg", type: "image/svg+xml" },
            { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
        ],
        apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
    },
    appleWebApp: {
        capable: true,
        statusBarStyle: "default",
        title: "Messages",
        // Native iOS launch screens (generated by `yarn icons`).
        startupImage: splashScreens,
    },
    formatDetection: { telephone: false, email: false, address: false },
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
    interactiveWidget: "resizes-content",
    themeColor: [
        { media: "(prefers-color-scheme: light)", color: "#ffffff" },
        { media: "(prefers-color-scheme: dark)", color: "#000000" },
    ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" dir="ltr" suppressHydrationWarning>
            <head>
                {/* Apply the saved appearance before first paint to avoid a flash. */}
                <script dangerouslySetInnerHTML={{ __html: APPEARANCE_BOOT_SCRIPT }} />
                <meta name="mobile-web-app-capable" content="yes" />
            </head>
            <body>
                {/*
                 * Launch splash, sent with the HTML so it paints immediately (and from the
                 * service-worker cache when offline). It matches the iOS launch images and
                 * fades out once the app has loaded its session (see AppShell).
                 */}
                <div id="app-splash" className="app-splash" aria-hidden="true">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src="/icon.svg" alt="" className="app-splash__icon" />
                    <div className="app-splash__spinner">
                        <Spinner size={22} />
                    </div>
                </div>
                <ServiceWorkerRegister />
                {children}
            </body>
        </html>
    );
}
