/**
 * The app icon as iOS presents it: the full-bleed artwork (public/icon.svg,
 * generated by `yarn icons`) under the ~22.37% continuous-corner mask.
 */
export function AppIcon({ size = 96 }: { size?: number }) {
    return (
        <span
            aria-hidden
            className="block shrink-0 overflow-hidden shadow-[0_12px_32px_rgb(0_0_0/0.18),0_0_0_0.5px_rgb(0_0_0/0.08)]"
            style={{ width: size, height: size, borderRadius: size * 0.2237 }}
        >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
                src="/icon.svg"
                alt=""
                width={size}
                height={size}
                className="size-full"
            />
        </span>
    );
}
